general:
  batch_size: 2
  device: cpu
  mode: train
  epoch: 2
  valid_size: 0.1
  test_size: 0.1
  max_length: 512
  n_worker: 0
  plm: xlmr
  save_ckpt_per_n_epoch: 1 
  logging_per_steps: 100
  evaluate_per_step: 1000
  accumulation_steps: 2
  
path: 
  pretrained_dir: ../pretrained
  train_data: ../data/hltar-data/test
  test_data: ../data/hltar-data/test
  val_data: ../data/hltar-data/test
  warm_up: checkpoints/cross_1.bin
  ckpt: outputs/checkpoints
  log: outputs/logs
  bm25: outputs/bm25
  embedd_model: outputs/checkpoints/dual_0.bin
