reranker:
  plm: xlmr
  batch_size: 2
  max_length: 512
  pretrained_dir: /mnt/sda2/datas/mbf_ir/pretrained
  ckpt_path: /mnt/sda2/datas/mbf_ir/ckpts/reranker/cross_epoch=1_step=79999.bin
  device: cpu

retriever:
  plm: sbert
  max_length: 256
  index_dir: /mnt/sda2/datas/mbf_ir/demo/checkpoints/retriever
  ckpt_path: /mnt/sda2/datas/mbf_ir/pretrained
  vncorenlp_dir: /home/tuyendv/Desktop/retriever/vncorenlp
  pretrained_dir: /mnt/sda2/datas/mbf_ir/pretrained

bm25:
  ckpt_path: /mnt/sda2/datas/mbf_ir/demo/checkpoints/bm25

